### PR TITLE
WIP: Bump compiler to 20170521

### PR DESCRIPTION
**Pull request by YurySolovyov**
- [ ] Fix tests

### CODE REVIEW

**Comment by YurySolovyov** [comment]
@knowtheory I've fixed all tests except for 2 dealing with libraries. I'm not sure what's the best way to approach them other than just re-generating fixtures using newer compiler.
I also replaced some `assert`s with `assert_equal` to get better diffing from minitest.
Anyway, please take a look

**Comment by YurySolovyov** [comment]
@knowtheory any plans for release? or you're evaluating it internally?

**Comment by knowtheory** [comment]
Sorry, i've been crazy swamped, just updated the gem and pushed it! https://rubygems.org/gems/closure-compiler

**Comment by PikachuEXE** [comment]
Great, should the README be updated too?

**Comment by PikachuEXE** [comment]
Just realized that `1.1.13` tag is missing

**Comment by YurySolovyov** [comment]
@PikachuEXE updated readme

**Comment by PikachuEXE** [comment]
Thanks :)
How about the missing tag ?

**Pull request merged**
